version: '3.8'
services:
  app:
    build: ./app/
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
    depends_on:
      - database
    restart: on-failure

  web-proxy:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
      - database
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  database:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./postgres/.env
    command: bash -c "printenv | grep POSTGRES_ && docker-entrypoint.sh postgres"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - ./rabbitmq/.env
    ports:
      - "5353:5353"
      - "5672:5672"
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
    restart: on-failure

  worker:
    build: ./app/
    image: worker
    working_dir: /app
    volumes:
      - ./app:/app
    command: python -u worker.py
    depends_on:
      - rabbitmq
      - database
    restart: always

    
