version: '3.8'
services:
  app:
    build: ./app/
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
    depends_on:
      - database
      - rabbitmq
    restart: on-failure
    # command: /bin/sh "dvc pull"

  web-proxy:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  rabbitmq:
    image: rabbitmq:3.13.3-management
    env_file:
      - ./rabbitmq/.env
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
    restart: on-failure

  database:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./postgres/.env
    command: bash -c "printenv | grep POSTGRES_ && docker-entrypoint.sh postgres"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    
